language: node_js
node_js: stable

env:
  global:
    - GH_CI_REF: github.com/iootclab/iootclab.github.io.git

branches:
  only:
    - master

# https://docs.travis-ci.com/user/job-lifecycle
# http://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html
before_install:
  - git config --global user.name "Johnathon"
  - git config --global user.email "johnathon.btc@gmail.com"

install:
  - npm install hexo

script:
- hexo clean
- hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Auto build by Travis CI."
  - git push --force --quiet "https://${GH_CI_TOKEN}@${GH_CI_REF}" master


