# language: node_js
# node_js: stable

# # https://docs.travis-ci.com/user/job-lifecycle
# install:
#   - npm install hexo

# script:
# - hexo clean
# - hexo g

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "Johnathon"
#   - git config user.email "johnathon.btc@gmail.com"
#   - git add .
#   - git commit -m "Auto build by Travis CI."
#   - git push --force --quiet "https://${GH_CI_TOKEN}@${GH_CI_REF}" master

# branches:
#   only:
#     - master

# env:
#   global:
#     - GH_CI_REF: github.com/iootclab/iootclab.github.io.git

language: node_js
node_js: stable
branches:
  only:
    - master

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_install:
  - git config --global user.name "Johnathon"
  - git config --global user.email "johnathon.btc@gmail.com"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli

install:
  - yarn

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Auto build by Travis CI."
  - git push --quiet --force https://$REPO_TOKEN@github.com/iootclab/iootclab.github.io.git master

