language: node_js
node_js: stable
env:
  global:
  - GH_CI_REF: github.com/iootclab/iootclab.github.io.git
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_907e9e66a763_key -iv $encrypted_907e9e66a763_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- git config --global user.name "Johnathon"
- git config --global user.email "johnathon.btc@gmail.com"
install:
- npm install hexo
script:
- hexo clean
- hexo g
after_script:
- cd ./public
- git init
- git add .
- git commit -m "Auto build by Travis CI."
- git push --force --quiet "https://${GH_CI_TOKEN}@${GH_CI_REF}" master
