language: node_js
node_js: stable

branches:
  only:
    - master

# https://docs.travis-ci.com/user/job-lifecycle
install:
  - npm install hexo

script:
- hexo clean
- hexo g

after_success:
  - cd ./public
  - git init
  - git config user.name "Johnathon"
  - git config user.email "johnathon.btc@gmail.com"
  - git add .
  - git commit -m "Auto build by Travis CI."
  - git push --force --quiet "https://${GH_CI_TOKEN}@${GH_CI_REF}" master:master

env:
  global:
    - GH_CI_REF: github.com/iootclab/iootclab.github.io

